name: Run tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: latest
        leiningen: latest
    - name: Run tests with kaocha
      run: clj -A:1.10:test:kaocha
    - name: Run tests with leiningen
      run: lein test-all
